CREATE TABLE recruiter_tracker (
  id INT AUTO_INCREMENT PRIMARY KEY,
  date_contacted DATE,
  recruiter_name VARCHAR(255) NOT NULL,
  company VARCHAR(255) NOT NULL,
  role_level VARCHAR(100),
  role_type VARCHAR(100),
  location VARCHAR(255),
  comp_range VARCHAR(100),
  status VARCHAR(100) NOT NULL,
  relationship_status VARCHAR(100),
  phone VARCHAR(50),
  email VARCHAR(255),
  address VARCHAR(255),
  website VARCHAR(255),
  notes TEXT,
  reported_to_unemployment VARCHAR(10) DEFAULT 'No',
  follow_up_date DATE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);